### REGISTER USER 1
POST http://localhost:5001/users
Content-Type: application/json

{
    "lastname": "Tom13",
    "firstname": "tom13",
    "email": "tom13@tom.com",
    "password": "Azerty123456!",
    "role": "admin"
}

### GET USER 1
GET http://localhost:5001/users/483c7ac4-d625-411c-ba69-7cf54dd60740

### LOGIN USER 1
POST http://localhost:5001/security/login
Content-Type: application/json

{
    "email": "tom13@tom.com",
    "password": "Azerty123456!"
}

### TRY Token Bearer USER 1 (ADMIN ONLY)
GET http://localhost:5001/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI4OGM5ZGVmYS1jYWJmLTQ4ZDktYWJiOS0xYWMyZGJjYWNjZjEiLCJmdWxsTmFtZSI6InRvbTEzIFRvbTEzIiwiaWF0IjoxNzE2MTEwNjUxfQ.wSg-q2bdKYL8SOLrAuNkjoDeJhORQm8hJbZL1xesriE

### REGISTER USER 2
POST http://localhost:5001/users
Content-Type: application/json

{
    "lastname": "Tom9",
    "email": "tom9@tom.com",
    "password": "Azerty123456!"
}

### GET USER 2
GET http://localhost:5001/users/c944ceb9-d3ce-4d73-9902-2c6a1d4560ca

### LOGIN USER 2
POST http://localhost:5001/security/login
Content-Type: application/json

{
    "email": "tom9@tom.com",
    "password": "Azerty123456!"
}

### TRY Token Bearer USER 2 (ADMIN ONLY)
GET http://localhost:5001/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJjOTQ0Y2ViOS1kM2NlLTRkNzMtOTkwMi0yYzZhMWQ0NTYwY2EiLCJmdWxsTmFtZSI6Im51bGwgVG9tOSIsImlhdCI6MTcxNDE0MDA0N30.y33c4taM7QR8K6mndHjJNxSW4KDimWQAHo2ENBMXy3I