### creer une partie
POST http://localhost:5001/game/create
Content-Type: application/json

{
    "creatorId":"483c7ac4-d625-411c-ba69-7cf54dd60740"
}

### Voir les parties en cours
GET http://localhost:5001/game

##### Supprime toutes les parties en cours (ADMIN ONLY)
DELETE http://localhost:5001/game/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI4OGM5ZGVmYS1jYWJmLTQ4ZDktYWJiOS0xYWMyZGJjYWNjZjEiLCJmdWxsTmFtZSI6InRvbTEzIFRvbTEzIiwiaWF0IjoxNzE2MTEwNjUxfQ.wSg-q2bdKYL8SOLrAuNkjoDeJhORQm8hJbZL1xesriE


### Rejoindre une partie (id de la game dans l'url)
POST http://localhost:5001/game/join/ce49ec0e-8b8d-4871-aa27-a6712246aefb
Content-Type: application/json 

{
    "playerId":"c944ceb9-d3ce-4d73-9902-2c6a1d4560ca"
}


### Make Move (id game + user 1) 
POST http://localhost:5001/game/play/ce49ec0e-8b8d-4871-aa27-a6712246aefb
Content-Type: application/json 

{
    "playerId":"483c7ac4-d625-411c-ba69-7cf54dd60740",
    "move": 2
}

### Make Move (id game + user 2)
POST http://localhost:5001/game/play/ce49ec0e-8b8d-4871-aa27-a6712246aefb
Content-Type: application/json 

{
    "playerId":"c944ceb9-d3ce-4d73-9902-2c6a1d4560ca",
    "move": 7
}

### Terminer une partie (id de la game dans l'url)
DELETE http://localhost:5001/game/end/ce49ec0e-8b8d-4871-aa27-a6712246aefb